FROM ubuntu

RUN apt-get update && apt-get install -y tar && rm -rf /var/lib/apt/lists/*

WORKDIR /descompresion

# Copia el archivo imagen.tar desde el host al contenedor
COPY imagen.tar .

# Descomprime el archivo imagen.tar
RUN tar -xvf imagen.tar && rm imagen.tar