FROM php:8.1-apache
RUN docker-php-ext-install mysqli pdo pdo_mysql
RUN apt update
RUN apt install wget
RUN wget -O phpunit https://phar.phpunit.de/phpunit-10.phar
RUN chmod +x phpunit
RUN mv phpunit /usr/local/bin/phpunit